# 🔢 NumPy Fundamentals for Machine Learning

Welcome to the first notebook in your Machine Learning journey! NumPy is the foundation of nearly all data science and ML work in Python.

## 📚 What You'll Learn

1. **Array Creation** - Creating and initializing arrays
2. **Array Operations** - Mathematical and logical operations
3. **Indexing & Slicing** - Accessing elements and subsets
4. **Broadcasting** - Powerful array operations
5. **Linear Algebra** - Essential matrix operations
6. **Random Numbers** - Statistical computing
7. **Performance Tips** - Why NumPy is fast

## 🎯 Prerequisites
- Basic Python knowledge
- Understanding of lists and loops

## ⏱️ Estimated Time: 2-3 hours

---

## 1. Introduction to NumPy

NumPy (Numerical Python) is the core library for numerical computing in Python. It provides:

- **ndarray**: A powerful N-dimensional array object
- **Broadcasting**: Functions that operate element-wise on arrays
- **Linear Algebra**: Matrix operations and decompositions
- **Random Number Generation**: Statistical distributions

### Why NumPy?

1. **Speed**: NumPy is written in C, making it 10-100x faster than pure Python
2. **Memory Efficiency**: Arrays use less memory than Python lists
3. **Vectorization**: Replace loops with array operations
4. **Integration**: Works seamlessly with Pandas, Scikit-learn, TensorFlow, etc.

In [7]:
# Import NumPy - the standard convention is to import as 'np'
import numpy as np

# Check the version
print(f"NumPy version: {np.__version__}")

NumPy version: 2.4.0


---
## 2. Creating Arrays

NumPy arrays are the building blocks of data science. Let's explore different ways to create them.

### 2.1 From Python Lists

In [8]:
# Creating a 1D array from a list
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(arr_1d)
print(f"Shape: {arr_1d.shape}")
print(f"Dimensions: {arr_1d.ndim}")
print(f"Data type: {arr_1d.dtype}")
print()

1D Array:
[1 2 3 4 5]
Shape: (5,)
Dimensions: 1
Data type: int64



In [ ]:
# Creating a 2D array (matrix)
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array (Matrix):")
print(arr_2d)
print(f"Shape: {arr_2d.shape}")
print(f"Dimensions: {arr_2d.ndim}")
print(f"Total elements: {arr_2d.size}")

2D Array (Matrix):
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Dimensions: 2
Total elements: 9


### 2.2 Using NumPy Functions

These array creation functions are essential building blocks in ML:

| Function | ML Use Case |
|----------|-------------|
| `np.zeros()` | Initialize weight matrices, create placeholder arrays for results |
| `np.ones()` | Bias initialization, creating masks, normalization denominators |
| `np.eye()` | Identity matrices for linear algebra, regularization in regression |
| `np.arange()` | Creating index arrays, batch indices for training |
| `np.linspace()` | Plotting decision boundaries, creating smooth curves for visualization |

In [10]:
# ============================================================
# ZEROS ARRAY: np.zeros()
# ============================================================
# In ML, zeros are commonly used to:
# 1. Initialize weight matrices (though random init is often preferred)
# 2. Create empty arrays to store predictions or gradients
# 3. Pad sequences to equal length (NLP tasks)
# 4. Create placeholder tensors before filling with data

zeros = np.zeros((3, 4))
print("Zeros (3x4):")
print(zeros)
print()

Zeros (3x4):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]



In [ ]:
# ============================================================
# ONES ARRAY: np.ones()
# ============================================================
# In ML, ones are commonly used to:
# 1. Initialize bias terms (often start at 1 or 0)
# 2. Create masks for attention mechanisms (transformers)
# 3. Add a column of 1s for the bias term in linear regression
# 4. Create weight arrays before scaling
# 5. Broadcasting multipliers

ones = np.ones((2, 3))
print("Ones (2x3):")
print(ones)
print()

Ones (2x3):
[[1. 1. 1.]
 [1. 1. 1.]]



In [ ]:
# ============================================================
# FILLED ARRAY: np.full()
# ============================================================
# In ML, filled arrays are used for:
# 1. Creating constant baseline predictions
# 2. Initializing all weights to a specific value
# 3. Creating padding tokens with specific values (e.g., -1 for masking)
# 4. Setting up arrays with placeholder values before computation

filled = np.full((2, 2), 7)
print("Filled with 7:")
print(filled)
print()

Filled with 7:
[[7 7]
 [7 7]]



In [ ]:
# ============================================================
# IDENTITY MATRIX: np.eye()
# ============================================================
# The identity matrix I is crucial in ML for:
#
# 1. RIDGE REGRESSION (L2 Regularization):
#    β = (X^T X + λI)^(-1) X^T y
#    The λI term prevents overfitting by shrinking coefficients
#
# 2. MATRIX INVERSE VERIFICATION:
#    A @ A_inv should equal I (identity)
#
# 3. EIGENVALUE PROBLEMS:
#    det(A - λI) = 0 is used to find eigenvalues
#
# 4. INITIALIZATION:
#    Sometimes weights are initialized close to identity
#    to preserve input information in early training
#
# 5. COVARIANCE REGULARIZATION:
#    Adding small I to covariance matrices ensures invertibility

identity = np.eye(4)
print("Identity Matrix (4x4):")
print(identity)

Identity Matrix (4x4):
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# ============================================================
# ARANGE vs LINSPACE
# ============================================================
# arange: When you know the STEP SIZE
#   - Creating batch indices: np.arange(0, len(data), batch_size)
#   - Epoch counting: np.arange(num_epochs)
#   - Feature indices for selection
#
# linspace: When you know the NUMBER OF POINTS
#   - Plotting smooth curves for decision boundaries
#   - Creating evaluation points for model predictions
#   - Generating x-axis values for loss curves
#   - Feature scaling: np.linspace(0, 1, num_samples) for normalization

# Range of values
range_arr = np.arange(0, 10, 2)  # start, stop, step
print(f"arange(0, 10, 2): {range_arr}")

# Evenly spaced values
linspace_arr = np.linspace(0, 1, 5)  # start, stop, num_points
print(f"linspace(0, 1, 5): {linspace_arr}")

arange(0, 10, 2): [0 2 4 6 8]
linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]


### 💡 Key Insight: arange vs linspace

- `arange(start, stop, step)` - You specify the step size
- `linspace(start, stop, num)` - You specify how many points

Use `linspace` when you need exactly N evenly-spaced points!

---
## 3. Array Indexing and Slicing

Accessing elements in arrays is fundamental. NumPy uses zero-based indexing like Python.

In [15]:
# Create a sample array
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(f"Original array: {arr}")

Original array: [ 10  20  30  40  50  60  70  80  90 100]


In [16]:
# Basic indexing
print(f"First element (index 0): {arr[0]}")
print(f"Last element (index -1): {arr[-1]}")
print(f"Third element (index 2): {arr[2]}")

First element (index 0): 10
Last element (index -1): 100
Third element (index 2): 30


In [17]:
# Slicing: arr[start:stop:step]
print(f"Elements 2-5: {arr[2:6]}")
print(f"First 5 elements: {arr[:5]}")
print(f"Last 3 elements: {arr[-3:]}")
print(f"Every other element: {arr[::2]}")
print(f"Reversed: {arr[::-1]}")

Elements 2-5: [30 40 50 60]
First 5 elements: [10 20 30 40 50]
Last 3 elements: [ 80  90 100]
Every other element: [10 30 50 70 90]
Reversed: [100  90  80  70  60  50  40  30  20  10]


### 3.1 2D Array Indexing

Syntax: `matrix[row, column]` or `matrix[row_slice, column_slice]`

**Why 2D indexing matters in ML:**

- **Feature selection**: Extracting specific columns (features) from datasets- **Image processing**: Accessing pixel regions (row, column)

- **Batch processing**: Selecting rows of samples for mini-batch training- **Weight matrices**: Accessing specific neurons or layers

In [ ]:
# Create a 2D array
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Matrix:")
print(matrix)
print(f"Shape: {matrix.shape}")

Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)


In [19]:
# Accessing elements: matrix[row, column]
print(f"Element at (0, 0): {matrix[0, 0]}")
print(f"Element at (1, 2): {matrix[1, 2]}")
print(f"Element at (2, -1): {matrix[2, -1]}")

Element at (0, 0): 1
Element at (1, 2): 7
Element at (2, -1): 12


In [20]:
# Slicing rows and columns
print("First row:")
print(matrix[0, :])
print()
print("First column:")
print(matrix[:, 0])
print()
print("Submatrix (rows 0-1, cols 1-2):")
print(matrix[0:2, 1:3])

First row:
[1 2 3 4]

First column:
[1 5 9]

Submatrix (rows 0-1, cols 1-2):
[[2 3]
 [6 7]]


### 3.2 Boolean Indexing (Very Important for ML!)

| **Train/test by condition** | `data[data['split'] == 'train']` |

Boolean indexing creates a mask of True/False values to filter arrays.| **Feature selection** | `X[:, importance > 0.1]` |

This is one of the **most powerful tools** for data preprocessing in ML:| **Threshold predictions** | `pred[pred > 0.5] = 1` |

| **Handle missing data** | `data[~np.isnan(data)]` |

| Use Case | Example || **Filter by class** | `X[y == 1]` for class 1 samples |

|----------|--------|| **Remove outliers** | `data[data < 3 * std]` |

In [21]:
# Create sample data
data = np.array([15, 22, 8, 45, 30, 12, 55, 18])
print(f"Data: {data}")

Data: [15 22  8 45 30 12 55 18]


In [22]:
# Boolean mask
mask = data > 20
print(f"Mask (data > 20): {mask}")

Mask (data > 20): [False  True False  True  True False  True False]


In [23]:
# Apply mask to filter data
filtered = data[mask]
print(f"Values > 20: {filtered}")

# Shorthand (most common usage)
print(f"Values between 15 and 40: {data[(data >= 15) & (data <= 40)]}")

Values > 20: [22 45 30 55]
Values between 15 and 40: [15 22 30 18]


### 💡 Key Insight: Boolean Indexing in ML

Boolean indexing is used constantly in ML for:
- Filtering outliers
- Selecting data by conditions
- Data cleaning
- Feature selection

---
## 4. Array Operations

NumPy shines in element-wise operations. No more loops needed!

In [24]:
# Create sample arrays
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print(f"a = {a}")
print(f"b = {b}")

a = [1 2 3 4]
b = [5 6 7 8]


In [25]:
# Arithmetic operations (element-wise)
print(f"a + b = {a + b}")
print(f"a - b = {a - b}")
print(f"a * b = {a * b}")  # Element-wise, NOT matrix multiplication
print(f"a / b = {a / b}")
print(f"a ** 2 = {a ** 2}")

a + b = [ 6  8 10 12]
a - b = [-4 -4 -4 -4]
a * b = [ 5 12 21 32]
a / b = [0.2        0.33333333 0.42857143 0.5       ]
a ** 2 = [ 1  4  9 16]


In [26]:
# Scalar operations (broadcasting)
print(f"a * 10 = {a * 10}")
print(f"a + 100 = {a + 100}")

a * 10 = [10 20 30 40]
a + 100 = [101 102 103 104]


### 4.1 Universal Functions (ufuncs)

In [ ]:
x = np.array([0, np.pi / 4, np.pi / 2, np.pi])

print("Trigonometric functions:")
print(f"sin(x) = {np.sin(x)}")
print(f"cos(x) = {np.cos(x)}")
print()

Trigonometric functions:
sin(x) = [0.00000000e+00 7.07106781e-01 1.00000000e+00 1.22464680e-16]
cos(x) = [ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -1.00000000e+00]



In [28]:
y = np.array([1, 10, 100, 1000])

print("Logarithmic functions:")
print(f"log(y) = {np.log(y)}")
print(f"log10(y) = {np.log10(y)}")
print(f"exp([1,2,3]) = {np.exp([1, 2, 3])}")

Logarithmic functions:
log(y) = [0.         2.30258509 4.60517019 6.90775528]
log10(y) = [0. 1. 2. 3.]
exp([1,2,3]) = [ 2.71828183  7.3890561  20.08553692]


### 4.2 Aggregation Functions (Statistical Operations)

These functions are the backbone of ML data analysis:

| Function | ML Application |
|----------|----------------|
| `np.mean()` | Calculate average loss, feature means for normalization |
| `np.std()` | Feature standardization: `(x - mean) / std` |
| `np.var()` | Explained variance in PCA, model uncertainty |
| `np.min/max()` | Min-Max scaling: `(x - min) / (max - min)` |
| `np.sum()` | Total loss, counting, aggregating predictions |
| `np.argmin/argmax()` | Find index of best/worst prediction, class prediction in classification |

In [ ]:
# ============================================================
# AGGREGATION FUNCTIONS - Essential for ML
# ============================================================
# These operations are used constantly in ML:
# - mean/std: Feature normalization and standardization
# - sum: Computing total loss across samples
# - min/max: Finding best models, min-max scaling
# - argmin/argmax: Predicting class labels in classification
#   Example: predicted_class = np.argmax(softmax_output)

data = np.array([23, 45, 12, 67, 34, 89, 21, 56, 43])

print(f"Data: {data}")
print()
print(f"Mean: {np.mean(data):.2f}")  # Average for normalization
print(f"Median: {np.median(data)}")  # Robust to outliers
print(f"Std Dev: {np.std(data):.2f}")  # For standardization
print(f"Variance: {np.var(data):.2f}")  # For explained variance
print(f"Sum: {np.sum(data)}")  # Total loss, etc.
print(f"Min: {np.min(data)}, Max: {np.max(data)}")  # For scaling
print(f"Argmin: {np.argmin(data)}, Argmax: {np.argmax(data)}")  # For class prediction

Data: [23 45 12 67 34 89 21 56 43]

Sum: 390
Mean: 43.33
Median: 43.0
Std Dev: 23.07
Variance: 532.22
Min: 12, Max: 89
Argmin: 2, Argmax: 5


### 4.3 Aggregation Along Axes

In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix:")
print(matrix)
print()

print(f"Sum of all: {np.sum(matrix)}")
print(f"Sum along axis 0 (columns): {np.sum(matrix, axis=0)}")
print(f"Sum along axis 1 (rows): {np.sum(matrix, axis=1)}")
print()
print(f"Mean of each column: {np.mean(matrix, axis=0)}")
print(f"Mean of each row: {np.mean(matrix, axis=1)}")

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sum of all: 45
Sum along axis 0 (columns): [12 15 18]
Sum along axis 1 (rows): [ 6 15 24]

Mean of each column: [4. 5. 6.]
Mean of each row: [2. 5. 8.]


### 💡 Understanding Axes

- **axis=0**: Operations along rows (collapse rows, keep columns)
- **axis=1**: Operations along columns (collapse columns, keep rows)

Think of it as: "which axis do I want to reduce/eliminate?"

---
## 5. Reshaping Arrays

**Reshaping is CRITICAL in ML** - Most ML errors come from shape mismatches!

- `(batch_size, channels, height, width)` - CNN input (PyTorch)

| Operation | ML Use Case |- `(batch_size, height, width, channels)` - CNN input (TensorFlow)

|-----------|-------------|- `(batch_size, seq_len, features)` - RNN/Transformer input

| `reshape(-1, 1)` | Convert 1D array to column vector for sklearn |- `(n_samples, n_features)` - Standard sklearn input

| `reshape(batch, height, width, channels)` | Prepare images for CNN |**Common shape patterns in ML:**

| `flatten()` | Convert image to 1D for fully connected layers |

| `transpose()` | Swap features and samples, attention mechanisms || `reshape(-1)` | Flatten predictions for evaluation |

In [ ]:
# ============================================================
# RESHAPING FOR ML
# ============================================================
# Reshaping is needed constantly:

# - sklearn expects 2D input: X.reshape(-1, 1) for single featureprint(f"Shape: {arr.shape}")

# - Neural networks expect specific tensor shapesprint(f"Original: {arr}")

# - Image data needs (batch, H, W, C) or (batch, C, H, W)arr = np.arange(12)

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape: (12,)


In [32]:
# Reshape to 2D
reshaped = arr.reshape(3, 4)
print("Reshaped to (3, 4):")
print(reshaped)

Reshaped to (3, 4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# ============================================================
# AUTO-CALCULATE DIMENSION WITH -1
# ============================================================
# The -1 is incredibly useful - NumPy calculates the missing dimension
# Common ML patterns:

#   X.reshape(-1, 1)  -> Single feature column for sklearnprint(f"Shape: {auto_reshaped.shape}")

#   X.reshape(1, -1)  -> Single sample rowprint(auto_reshaped)

#   X.reshape(-1)     -> Flatten to 1D (like for y_pred comparison)print("Auto-reshaped to (4, ?):")

#   X.reshape(batch_size, -1)  -> Flatten images keeping batch dimensionauto_reshaped = arr.reshape(4, -1)  # 4 rows, auto columns

Auto-reshaped to (4, ?):
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Shape: (4, 3)


In [34]:
# Flatten back to 1D
flattened = reshaped.flatten()
print(f"Flattened: {flattened}")

# Or use ravel (returns view when possible)
raveled = reshaped.ravel()
print(f"Raveled: {raveled}")

Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
# ============================================================
# TRANSPOSE - Essential for Linear Algebra in ML
# ============================================================
# Transpose swaps rows and columns: shape (m, n) -> (n, m)
#
# Critical ML uses:
# 1. Matrix multiplication: X.T @ X (for normal equation)
# 2. Covariance matrix computation
# 3. Attention mechanisms: Q @ K.T

# 4. Converting row vectors to column vectorsprint(f"Shape: {matrix.T.shape}")

# 5. Feature matrix manipulationprint(matrix.T)

print("Transposed:")

matrix = np.array([[1, 2, 3], [4, 5, 6]])print()

print("Original:")print(f"Shape: {matrix.shape}")
print(matrix)

Original:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

Transposed:
[[1 4]
 [2 5]
 [3 6]]
Shape: (3, 2)


---
## 6. Broadcasting

**Broadcasting is NumPy's "magic" for performing operations on arrays of different shapes.**

This is NOT just a convenience feature - it's essential for efficient ML code!

### Why It Matters:
- **Speed**: Broadcasting uses optimized C code, not Python loops
- **Memory**: No need to replicate arrays to match shapes
- **Readability**: Code looks like mathematical notation

### ML Applications of Broadcasting:

| Operation | Without Broadcasting | With Broadcasting |
|-----------|---------------------|------------------|
| Feature normalization | Loop over features | `(X - mean) / std` |
| Bias addition | Loop over samples | `X @ W + b` |
| Distance calculation | Nested loops | `X - centroids[:, np.newaxis]` |
| Softmax denominator | Complex loops | `exp / sum.reshape(-1, 1)` |

In [36]:
# Simple broadcasting: scalar + array
arr = np.array([1, 2, 3])
print(f"arr + 10 = {arr + 10}")

arr + 10 = [11 12 13]


In [ ]:
# Broadcasting with 2D arrays
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_vector = np.array([10, 20, 30])

print("Matrix:")
print(matrix)
print(f"Row vector: {row_vector}")
print()
print("Matrix + Row vector:")
print(matrix + row_vector)

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Row vector: [10 20 30]

Matrix + Row vector:
[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [ ]:
# Column vector broadcasting
col_vector = np.array([[100], [200], [300]])
print(f"Column vector shape: {col_vector.shape}")
print()
print("Matrix + Column vector:")
print(matrix + col_vector)

### Broadcasting Rules

1. If arrays have different number of dimensions, pad the smaller one with 1s on the left
2. Arrays are compatible if dimensions are equal or one of them is 1
3. Output shape is the maximum along each dimension

Example:
```
Array A:  3 x 4
Array B:      4
Padded B: 1 x 4
Result:   3 x 4  ✓ Compatible!
```

---
## 7. Linear Algebra

**Linear algebra is THE mathematical foundation of ML.** Nearly every ML algorithm uses these concepts:

| Concept | ML Application |
|---------|----------------|
| **Matrix Multiplication** | Neural network forward pass, feature transformation |
| **Transpose** | Covariance computation, attention mechanisms |
| **Dot Product** | Similarity measures, attention scores, projections |
| **Inverse** | Solving linear regression (normal equation), Mahalanobis distance |
| **Determinant** | Checking if matrix is invertible, Gaussian distributions |
| **Eigenvalues/vectors** | PCA, understanding covariance, spectral clustering |
| **SVD** | Dimensionality reduction, recommendation systems, data compression |
| **Norm** | Regularization (L1, L2), distance calculations |

### Key Equations in ML:
- **Linear Regression**: $\hat{y} = X\beta$ and $\beta = (X^T X)^{-1} X^T y$
- **Neural Network Layer**: $a = \sigma(Wx + b)$
- **PCA**: Find eigenvectors of covariance matrix $X^T X$
- **Attention**: $\text{Attention}(Q, K, V) = \text{softmax}(QK^T / \sqrt{d_k})V$

In [ ]:
# ============================================================
# MATRIX MULTIPLICATION - The Core of Neural Networks
# ============================================================
# Matrix multiplication is THE fundamental operation in ML:
#
# 1. NEURAL NETWORK FORWARD PASS:
#    output = activation(weights @ input + bias)
#    Each layer is just matrix multiplication!
#
# 2. LINEAR REGRESSION:
#    predictions = X @ beta
#
# 3. ATTENTION MECHANISM (Transformers):
#    attention_scores = Q @ K.T  (query times key transpose)
#
# 4. FEATURE TRANSFORMATION:
#    transformed_features = original_features @ transformation_matrix

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix A:")
print(A)
print()
print("Matrix B:")
print(B)
print()

# Method 1: @ operator (Python 3.5+) - PREFERRED
print("A @ B (matrix multiplication):")
print(A @ B)
print()

# Method 2: np.dot
print("np.dot(A, B):")
print(np.dot(A, B))

Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]

A @ B (matrix multiplication):
[[19 22]
 [43 50]]

np.dot(A, B):
[[19 22]
 [43 50]]


In [39]:
# ⚠️ Important: * is element-wise, @ is matrix multiplication
print("A * B (element-wise):")
print(A * B)
print()
print("A @ B (matrix multiplication):")
print(A @ B)

A * B (element-wise):
[[ 5 12]
 [21 32]]

A @ B (matrix multiplication):
[[19 22]
 [43 50]]


In [ ]:
# ============================================================
# DOT PRODUCT - Similarity and Projections
# ============================================================
# The dot product measures how "similar" two vectors are:
#
# 1. COSINE SIMILARITY:
#    cos(theta) = (v1 · v2) / (||v1|| * ||v2||)
#    Used in: Word embeddings (Word2Vec), recommendation systems
#
# 2. ATTENTION SCORES:
#    score = query · key (measures relevance)
#
# 3. LINEAR PREDICTIONS:
#    y = x · weights (weighted sum of features)
#
# 4. PROJECTION:
#    Project v1 onto v2: (v1 · v2 / ||v2||²) * v2

v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print(f"v1 · v2 = {np.dot(v1, v2)}")
print(f"Manual: 1*4 + 2*5 + 3*6 = {1*4 + 2*5 + 3*6}")

# Cosine similarity example
cosine_sim = np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))
print(f"Cosine similarity: {cosine_sim:.4f}")

v1 · v2 = 32
Manual: 1*4 + 2*5 + 3*6 = 32


In [ ]:
# ============================================================
# MATRIX INVERSE - Solving Linear Systems
# ============================================================
# The inverse A⁻¹ is a matrix such that: A @ A⁻¹ = I (identity)
#
# CRITICAL ML APPLICATIONS:
#
# 1. LINEAR REGRESSION (Normal/Closed-form Solution):
#    β = (X^T X)^(-1) X^T y
#    This directly solves for optimal weights!
#
# 2. RIDGE REGRESSION (L2 Regularization):
#    β = (X^T X + λI)^(-1) X^T y
#    The λI term makes the matrix invertible and prevents overfitting
#
# 3. GAUSSIAN DISTRIBUTIONS:
#    Mahalanobis distance uses covariance inverse: (x-μ)^T Σ^(-1) (x-μ)
#
# 4. KALMAN FILTERS:
#    State estimation uses matrix inverses
#
# DETERMINANT:
# - det(A) ≠ 0 means A is invertible
# - det(A) ≈ 0 means A is "nearly singular" - numerically unstable!
# - Used in multivariate Gaussian: p(x) ∝ 1/sqrt(det(Σ))

A = np.array([[4, 7], [2, 6]])
print("Matrix A:")
print(A)

# Determinant
det = np.linalg.det(A)
print(f"\nDeterminant: {det}")
if abs(det) < 1e-10:
    print("⚠️ Warning: Near-zero determinant - matrix may not be invertible!")
else:
    print("✅ Determinant is non-zero - matrix is invertible")

# Inverse
A_inv = np.linalg.inv(A)
print("\nInverse of A:")
print(A_inv)

# Verify: A @ A_inv should be identity
print("\nA @ A_inv (should be identity):")
print(np.round(A @ A_inv, 10))

In [ ]:
# ============================================================
# EIGENVALUES & EIGENVECTORS - Foundation of Dimensionality Reduction
# ============================================================
# For a matrix A, eigenvalue λ and eigenvector v satisfy: A @ v = λ * v
# The eigenvector v doesn't change DIRECTION when multiplied by A,
# only gets SCALED by λ.
#
# WHY THIS MATTERS IN ML:
#
# 1. PRINCIPAL COMPONENT ANALYSIS (PCA):
#    - Eigenvectors of covariance matrix = principal components
#    - Eigenvalues = variance explained by each component
#    - Larger eigenvalue = more important direction
#    - Used to reduce dimensions while preserving variance
#
# 2. SPECTRAL CLUSTERING:
#    - Uses eigenvectors of graph Laplacian matrix
#    - Groups similar data points together
#
# 3. GOOGLE'S PAGERANK:
#    - Eigenvector of the web's link matrix
#    - Importance of a page = its eigenvector component
#
# 4. UNDERSTANDING DATA STRUCTURE:
#    - Eigenvectors show main directions of variation
#    - Eigenvalues show how much data varies in each direction
#
# 5. STABILITY ANALYSIS:
#    - Used in analyzing neural network dynamics

M = np.array([[4, 2], [1, 3]])
eigenvalues, eigenvectors = np.linalg.eig(M)

print("Matrix M:")
print(M)
print(f"\nEigenvalues: {eigenvalues}")
print("  → These represent the 'importance' or variance in each direction")
print("\nEigenvectors (as columns):")
print(eigenvectors)
print("  → These are the principal directions of the transformation")

# Verify: M @ v = λ * v
print("\n🔍 Verification that M @ v = λ * v:")
for i in range(len(eigenvalues)):
    v = eigenvectors[:, i]
    Mv = M @ v
    lambda_v = eigenvalues[i] * v
    print(f"  Eigenvector {i+1}: M@v = {Mv}, λ*v = {lambda_v}")

### 💡 Key ML Applications of Linear Algebra

| Operation | Algorithm | What It Does |
|-----------|-----------|-------------|
| **Matrix Multiplication** | Neural Networks | Forward pass: `output = W @ input + b` |
| **Matrix Multiplication** | Transformers | Attention: `Q @ K.T` computes similarity scores |
| **Transpose** | All | Shape manipulation, covariance: `X.T @ X` |
| **Inverse** | Linear Regression | Normal equation: `β = (XᵀX)⁻¹ Xᵀy` |
| **Inverse + Identity** | Ridge Regression | Regularized: `β = (XᵀX + λI)⁻¹ Xᵀy` |
| **Eigendecomposition** | PCA | Find principal components (directions of max variance) |
| **Eigendecomposition** | Spectral Clustering | Group data using graph eigenvectors |
| **SVD** | Recommendation | Matrix factorization for user-item predictions |
| **SVD** | NLP | Latent Semantic Analysis for topic modeling |
| **Norms** | Regularization | L1 (Lasso) and L2 (Ridge) penalties |
| **Dot Product** | Word2Vec | Similarity between word embeddings |

### 📝 Quick Reference - When to Use What:
- **Need to solve Ax = b?** → Use `np.linalg.solve(A, b)` (more stable than inverse)
- **Need eigenvalues for PCA?** → Use `np.linalg.eig()` or `np.linalg.svd()`
- **Matrix not invertible?** → Add regularization: `A + λI` or use pseudoinverse `np.linalg.pinv()`
- **Need matrix decomposition?** → SVD: `np.linalg.svd()` works for any matrix

---
## 8. Random Number Generation

**Random numbers are EVERYWHERE in ML:**

| Use Case | Why Randomness? |
|----------|----------------|
| **Weight Initialization** | Neural network weights must start random (not zero!) |
| **Data Shuffling** | Prevents model from learning data order |
| **Train/Test Split** | Random assignment ensures unbiased splits |
| **Dropout** | Randomly disable neurons during training |
| **Data Augmentation** | Random transforms (rotation, flip, noise) |

### ⚠️ CRITICAL: Reproducibility
Always set a **random seed** for reproducible experiments!
This ensures you can reproduce your results exactly.

| **Stochastic Gradient Descent** | Random mini-batch selection |
| **Bootstrapping** | Random resampling for ensemble methods |
| **Monte Carlo Methods** | Random sampling for estimation |

In [ ]:
# ============================================================
# SETTING RANDOM SEED - Critical for ML Reproducibility!
# ============================================================
# Without a seed, you get different results every run.
# This makes debugging impossible and papers unreproducible.
#
# Best practices:
# 1. Set seed at the start of every experiment
# 2. Use the same seed when comparing models
# 3. Report your seed in papers/documentation
# 4. For deep learning, also set seeds for PyTorch/TensorFlow

np.random.seed(42)  # 42 is a common choice (Hitchhiker's Guide reference!)

In [ ]:
# Random numbers from [0, 1)
rand_uniform = np.random.rand(3, 3)
print("Uniform random (3x3):")
print(rand_uniform)

In [ ]:
# Random integers
rand_int = np.random.randint(1, 100, size=(2, 5))
print("Random integers 1-100 (2x5):")
print(rand_int)

In [ ]:
# ============================================================
# NORMAL (GAUSSIAN) DISTRIBUTION - The Most Important Distribution in ML
# ============================================================
# Many things in ML assume or use normal distribution:
#
# 1. WEIGHT INITIALIZATION:
#    - Xavier/Glorot: N(0, 1/n_in)
#    - He initialization: N(0, 2/n_in) for ReLU
#
# 2. ADDITIVE NOISE:
#    - Regularization by adding Gaussian noise
#    - Data augmentation
#
# 3. GAUSSIAN PROCESSES:
#    - Bayesian ML uses Gaussian priors
#
# 4. BATCH NORMALIZATION:
#    - Normalizes activations to ~N(0, 1)

# np.random.randn() gives standard normal: mean=0, std=1
# For custom: mean + std * np.random.randn()

rand_normal = np.random.randn(1000)
print(
    f"Normal distribution - Mean: {rand_normal.mean():.3f}, Std: {rand_normal.std():.3f}"
)

# Custom mean and std (like weight initialization)
custom_normal = 0.01 * np.random.randn(100)  # Small weights for initialization
print(
    f"Small weights init - Mean: {custom_normal.mean():.4f}, Std: {custom_normal.std():.4f}"
)

In [ ]:
# Random choice
options = ["cat", "dog", "bird", "fish"]
choices = np.random.choice(options, size=5)
print(f"Random choices: {choices}")

In [ ]:
# Shuffle array in-place
arr = np.arange(10)
print(f"Original: {arr}")
np.random.shuffle(arr)
print(f"Shuffled: {arr}")

---
## 9. Performance: NumPy vs Python Lists

Let's see why NumPy is essential for ML - speed matters!

In [ ]:
import time

# Create large data
size = 1_000_000
python_list = list(range(size))
numpy_array = np.arange(size)

print(f"Data size: {size:,} elements")

In [ ]:
# Python list: square each element
start = time.time()
result_list = [x**2 for x in python_list]
python_time = time.time() - start
print(f"Python list: {python_time:.4f} seconds")

In [ ]:
# NumPy: square each element
start = time.time()
result_numpy = numpy_array**2
numpy_time = time.time() - start
print(f"NumPy array: {numpy_time:.4f} seconds")

In [ ]:
speedup = python_time / numpy_time
print(f"\n�� NumPy is {speedup:.1f}x faster!")

---
## 📝 Practice Exercises

Try these exercises to solidify your understanding!

### Exercise 1: Array Creation
Create a 5x5 matrix with values from 1 to 25.

In [ ]:
# Your code here
exercise_1 = None  # Replace with your solution

# Uncomment to check:
# print(exercise_1)

### Exercise 2: Filtering
Given the array below, find all values that are even AND greater than 10.

In [ ]:
data = np.array([5, 12, 7, 18, 3, 22, 15, 8, 30, 11])

# Your code here
exercise_2 = None  # Replace with your solution

# Expected output: [12, 18, 22, 30]

### Exercise 3: Matrix Operations
Calculate the mean of each row and each column for the matrix below.

In [ ]:
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

# Your code here
row_means = None  # Replace with your solution
col_means = None  # Replace with your solution

# Expected: row_means = [20, 50, 80], col_means = [40, 50, 60]

### Exercise 4: Normalization (Common in ML!)
Normalize the array to have values between 0 and 1 using min-max scaling:

$$x_{normalized} = \frac{x - x_{min}}{x_{max} - x_{min}}$$

In [ ]:
original = np.array([10, 20, 30, 40, 50])

# Your code here
normalized = None  # Replace with your solution

# Expected output: [0., 0.25, 0.5, 0.75, 1.]

### Exercise 5: Linear Algebra
Solve the system of linear equations:
```
2x + 3y = 8
4x + 5y = 14
```
Hint: Use `np.linalg.solve(A, b)` where Ax = b

In [ ]:
# Your code here
A = None  # Coefficient matrix
b = None  # Right-hand side
solution = None  # Replace with your solution

# Expected output: x = 1, y = 2

---
## 📋 Solutions

Expand the cells below to see the solutions.

In [ ]:
# Solution 1
exercise_1 = np.arange(1, 26).reshape(5, 5)
print("Exercise 1 - 5x5 matrix:")
print(exercise_1)

In [ ]:
# Solution 2
data = np.array([5, 12, 7, 18, 3, 22, 15, 8, 30, 11])
exercise_2 = data[(data % 2 == 0) & (data > 10)]
print(f"Exercise 2 - Even AND > 10: {exercise_2}")

In [ ]:
# Solution 3
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
row_means = np.mean(matrix, axis=1)
col_means = np.mean(matrix, axis=0)
print(f"Exercise 3 - Row means: {row_means}")
print(f"Exercise 3 - Column means: {col_means}")

In [ ]:
# Solution 4
original = np.array([10, 20, 30, 40, 50])
normalized = (original - original.min()) / (original.max() - original.min())
print(f"Exercise 4 - Normalized: {normalized}")

In [ ]:
# Solution 5
A = np.array([[2, 3], [4, 5]])
b = np.array([8, 14])
solution = np.linalg.solve(A, b)
print(f"Exercise 5 - x = {solution[0]}, y = {solution[1]}")

---
## 🎯 Summary

### Key Concepts Covered

1. **Array Creation**: `np.array()`, `np.zeros()`, `np.ones()`, `np.arange()`, `np.linspace()`
2. **Indexing**: Zero-based, negative indexing, slicing with `[start:stop:step]`
3. **Boolean Indexing**: Filter arrays with conditions
4. **Operations**: Element-wise arithmetic, ufuncs, aggregations
5. **Axes**: `axis=0` for columns, `axis=1` for rows
6. **Broadcasting**: Automatic expansion of arrays for operations
7. **Linear Algebra**: `@` for matrix multiplication, `np.linalg` for advanced ops
8. **Random**: `np.random.seed()`, various distributions

### What's Next?

In the next notebook, we'll dive into **Pandas for Data Manipulation**, where you'll learn to work with real-world tabular data!

---

**Happy Learning! 🚀**