# 🔢 NumPy Fundamentals for Machine Learning

Welcome to the first notebook in your Machine Learning journey! NumPy is the foundation of nearly all data science and ML work in Python.

## 📚 What You'll Learn

1. **Array Creation** - Creating and initializing arrays
2. **Array Operations** - Mathematical and logical operations
3. **Indexing & Slicing** - Accessing elements and subsets
4. **Broadcasting** - Powerful array operations
5. **Linear Algebra** - Essential matrix operations
6. **Random Numbers** - Statistical computing
7. **Performance Tips** - Why NumPy is fast

## 🎯 Prerequisites
- Basic Python knowledge
- Understanding of lists and loops

## ⏱️ Estimated Time: 2-3 hours

---

## 1. Introduction to NumPy

NumPy (Numerical Python) is the core library for numerical computing in Python. It provides:

- **ndarray**: A powerful N-dimensional array object
- **Broadcasting**: Functions that operate element-wise on arrays
- **Linear Algebra**: Matrix operations and decompositions
- **Random Number Generation**: Statistical distributions

### Why NumPy?

1. **Speed**: NumPy is written in C, making it 10-100x faster than pure Python
2. **Memory Efficiency**: Arrays use less memory than Python lists
3. **Vectorization**: Replace loops with array operations
4. **Integration**: Works seamlessly with Pandas, Scikit-learn, TensorFlow, etc.

In [4]:
# Import NumPy - the standard convention is to import as 'np'
import numpy as np

# Check the version
print(f"NumPy version: {np.__version__}")

NumPy version: 2.4.0


---
## 2. Creating Arrays

NumPy arrays are the building blocks of data science. Let's explore different ways to create them.

### 2.1 From Python Lists

In [5]:
# Creating a 1D array from a list
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(arr_1d)
print(f"Shape: {arr_1d.shape}")
print(f"Dimensions: {arr_1d.ndim}")
print(f"Data type: {arr_1d.dtype}")
print()

1D Array:
[1 2 3 4 5]
Shape: (5,)
Dimensions: 1
Data type: int64



In [6]:
# Creating a 2D array (matrix)
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array (Matrix):")
print(arr_2d)
print(f"Shape: {arr_2d.shape}")
print(f"Dimensions: {arr_2d.ndim}")
print(f"Total elements: {arr_2d.size}")

2D Array (Matrix):
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Dimensions: 2
Total elements: 9


### 2.2 Using NumPy Functions

These array creation functions are essential building blocks in ML:

| Function | ML Use Case |
|----------|-------------|
| `np.zeros()` | Initialize weight matrices, create placeholder arrays for results |
| `np.ones()` | Bias initialization, creating masks, normalization denominators |
| `np.eye()` | Identity matrices for linear algebra, regularization in regression |
| `np.arange()` | Creating index arrays, batch indices for training |
| `np.linspace()` | Plotting decision boundaries, creating smooth curves for visualization |

In [7]:
# ============================================================
# ZEROS ARRAY: np.zeros()
# ============================================================
# In ML, zeros are commonly used to:
# 1. Initialize weight matrices (though random init is often preferred)
# 2. Create empty arrays to store predictions or gradients
# 3. Pad sequences to equal length (NLP tasks)
# 4. Create placeholder tensors before filling with data

zeros = np.zeros((3, 4))
print("Zeros (3x4):")
print(zeros)
print()

Zeros (3x4):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]



In [8]:
# ============================================================
# ONES ARRAY: np.ones()
# ============================================================
# In ML, ones are commonly used to:
# 1. Initialize bias terms (often start at 1 or 0)
# 2. Create masks for attention mechanisms (transformers)
# 3. Add a column of 1s for the bias term in linear regression
# 4. Create weight arrays before scaling
# 5. Broadcasting multipliers

ones = np.ones((2, 3))
print("Ones (2x3):")
print(ones)
print()

Ones (2x3):
[[1. 1. 1.]
 [1. 1. 1.]]



In [9]:
# ============================================================
# FILLED ARRAY: np.full()
# ============================================================
# In ML, filled arrays are used for:
# 1. Creating constant baseline predictions
# 2. Initializing all weights to a specific value
# 3. Creating padding tokens with specific values (e.g., -1 for masking)
# 4. Setting up arrays with placeholder values before computation

filled = np.full((2, 2), 7)
print("Filled with 7:")
print(filled)
print()

Filled with 7:
[[7 7]
 [7 7]]



In [10]:
# ============================================================
# IDENTITY MATRIX: np.eye()
# ============================================================
# The identity matrix I is crucial in ML for:
#
# 1. RIDGE REGRESSION (L2 Regularization):
#    β = (X^T X + λI)^(-1) X^T y
#    The λI term prevents overfitting by shrinking coefficients
#
# 2. MATRIX INVERSE VERIFICATION:
#    A @ A_inv should equal I (identity)
#
# 3. EIGENVALUE PROBLEMS:
#    det(A - λI) = 0 is used to find eigenvalues
#
# 4. INITIALIZATION:
#    Sometimes weights are initialized close to identity
#    to preserve input information in early training
#
# 5. COVARIANCE REGULARIZATION:
#    Adding small I to covariance matrices ensures invertibility

identity = np.eye(4)
print("Identity Matrix (4x4):")
print(identity)

Identity Matrix (4x4):
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
# ============================================================
# ARANGE vs LINSPACE
# ============================================================
# arange: When you know the STEP SIZE
#   - Creating batch indices: np.arange(0, len(data), batch_size)
#   - Epoch counting: np.arange(num_epochs)
#   - Feature indices for selection
#
# linspace: When you know the NUMBER OF POINTS
#   - Plotting smooth curves for decision boundaries
#   - Creating evaluation points for model predictions
#   - Generating x-axis values for loss curves
#   - Feature scaling: np.linspace(0, 1, num_samples) for normalization

# Range of values
range_arr = np.arange(0, 10, 2)  # start, stop, step
print(f"arange(0, 10, 2): {range_arr}")

# Evenly spaced values
linspace_arr = np.linspace(0, 1, 5)  # start, stop, num_points
print(f"linspace(0, 1, 5): {linspace_arr}")

arange(0, 10, 2): [0 2 4 6 8]
linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]


### 💡 Key Insight: arange vs linspace

- `arange(start, stop, step)` - You specify the step size
- `linspace(start, stop, num)` - You specify how many points

Use `linspace` when you need exactly N evenly-spaced points!

---
## 3. Array Indexing and Slicing

Accessing elements in arrays is fundamental. NumPy uses zero-based indexing like Python.

In [12]:
# Create a sample array
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(f"Original array: {arr}")

Original array: [ 10  20  30  40  50  60  70  80  90 100]


In [13]:
# Basic indexing
print(f"First element (index 0): {arr[0]}")
print(f"Last element (index -1): {arr[-1]}")
print(f"Third element (index 2): {arr[2]}")

First element (index 0): 10
Last element (index -1): 100
Third element (index 2): 30


In [14]:
# Slicing: arr[start:stop:step]
print(f"Elements 2-5: {arr[2:6]}")
print(f"First 5 elements: {arr[:5]}")
print(f"Last 3 elements: {arr[-3:]}")
print(f"Every other element: {arr[::2]}")
print(f"Reversed: {arr[::-1]}")

Elements 2-5: [30 40 50 60]
First 5 elements: [10 20 30 40 50]
Last 3 elements: [ 80  90 100]
Every other element: [10 30 50 70 90]
Reversed: [100  90  80  70  60  50  40  30  20  10]


### 3.1 2D Array Indexing

Syntax: `matrix[row, column]` or `matrix[row_slice, column_slice]`

**Why 2D indexing matters in ML:**

- **Feature selection**: Extracting specific columns (features) from datasets
- **Image processing**: Accessing pixel regions (row, column)
- **Batch processing**: Selecting rows of samples for mini-batch training
- **Weight matrices**: Accessing specific neurons or layers

In [15]:
# Create a 2D array
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Matrix:")
print(matrix)
print(f"Shape: {matrix.shape}")

Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)


In [16]:
# Accessing elements: matrix[row, column]
print(f"Element at (0, 0): {matrix[0, 0]}")
print(f"Element at (1, 2): {matrix[1, 2]}")
print(f"Element at (2, -1): {matrix[2, -1]}")

Element at (0, 0): 1
Element at (1, 2): 7
Element at (2, -1): 12


In [17]:
# Slicing rows and columns
print("First row:")
print(matrix[0, :])
print()
print("First column:")
print(matrix[:, 0])
print()
print("Submatrix (rows 0-1, cols 1-2):")
print(matrix[0:2, 1:3])

First row:
[1 2 3 4]

First column:
[1 5 9]

Submatrix (rows 0-1, cols 1-2):
[[2 3]
 [6 7]]


### 3.2 Boolean Indexing (Very Important for ML!)

Boolean indexing creates a mask of True/False values to filter arrays.

This is one of the **most powerful tools** for data preprocessing in ML:

| Use Case | Example |
|----------|--------|
| **Filter by class** | `X[y == 1]` for class 1 samples |
| **Remove outliers** | `data[data < 3 * std]` |
| **Train/test by condition** | `data[data['split'] == 'train']` |
| **Feature selection** | `X[:, importance > 0.1]` |
| **Threshold predictions** | `pred[pred > 0.5] = 1` |
| **Handle missing data** | `data[~np.isnan(data)]` |

In [18]:
# Create sample data
data = np.array([15, 22, 8, 45, 30, 12, 55, 18])
print(f"Data: {data}")

Data: [15 22  8 45 30 12 55 18]


In [19]:
# Boolean mask
mask = data > 20
print(f"Mask (data > 20): {mask}")

Mask (data > 20): [False  True False  True  True False  True False]


In [20]:
# Apply mask to filter data
filtered = data[mask]
print(f"Values > 20: {filtered}")

# Shorthand (most common usage)
print(f"Values between 15 and 40: {data[(data >= 15) & (data <= 40)]}")

Values > 20: [22 45 30 55]
Values between 15 and 40: [15 22 30 18]


### 💡 Key Insight: Boolean Indexing in ML

Boolean indexing is used constantly in ML for:
- Filtering outliers
- Selecting data by conditions
- Data cleaning
- Feature selection

---
## 4. Array Operations

NumPy shines in element-wise operations. No more loops needed!

In [21]:
# Create sample arrays
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print(f"a = {a}")
print(f"b = {b}")

a = [1 2 3 4]
b = [5 6 7 8]


In [22]:
# Arithmetic operations (element-wise)
print(f"a + b = {a + b}")
print(f"a - b = {a - b}")
print(f"a * b = {a * b}")  # Element-wise, NOT matrix multiplication
print(f"a / b = {a / b}")
print(f"a ** 2 = {a ** 2}")

a + b = [ 6  8 10 12]
a - b = [-4 -4 -4 -4]
a * b = [ 5 12 21 32]
a / b = [0.2        0.33333333 0.42857143 0.5       ]
a ** 2 = [ 1  4  9 16]


In [23]:
# Scalar operations (broadcasting)
print(f"a * 10 = {a * 10}")
print(f"a + 100 = {a + 100}")

a * 10 = [10 20 30 40]
a + 100 = [101 102 103 104]


### 4.1 Universal Functions (ufuncs)

In [24]:
x = np.array([0, np.pi / 4, np.pi / 2, np.pi])

print("Trigonometric functions:")
print(f"sin(x) = {np.sin(x)}")
print(f"cos(x) = {np.cos(x)}")
print()

Trigonometric functions:
sin(x) = [0.00000000e+00 7.07106781e-01 1.00000000e+00 1.22464680e-16]
cos(x) = [ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -1.00000000e+00]



In [25]:
y = np.array([1, 10, 100, 1000])

print("Logarithmic functions:")
print(f"log(y) = {np.log(y)}")
print(f"log10(y) = {np.log10(y)}")
print(f"exp([1,2,3]) = {np.exp([1, 2, 3])}")

Logarithmic functions:
log(y) = [0.         2.30258509 4.60517019 6.90775528]
log10(y) = [0. 1. 2. 3.]
exp([1,2,3]) = [ 2.71828183  7.3890561  20.08553692]


### 4.2 Aggregation Functions (Statistical Operations)

These functions are the backbone of ML data analysis:

| Function | ML Application |
|----------|----------------|
| `np.mean()` | Calculate average loss, feature means for normalization |
| `np.std()` | Feature standardization: `(x - mean) / std` |
| `np.var()` | Explained variance in PCA, model uncertainty |
| `np.min/max()` | Min-Max scaling: `(x - min) / (max - min)` |
| `np.sum()` | Total loss, counting, aggregating predictions |
| `np.argmin/argmax()` | Find index of best/worst prediction, class prediction in classification |

In [26]:
# ============================================================
# AGGREGATION FUNCTIONS - Essential for ML
# ============================================================
# These operations are used constantly in ML:
# - mean/std: Feature normalization and standardization
# - sum: Computing total loss across samples
# - min/max: Finding best models, min-max scaling
# - argmin/argmax: Predicting class labels in classification
#   Example: predicted_class = np.argmax(softmax_output)

data = np.array([23, 45, 12, 67, 34, 89, 21, 56, 43])

print(f"Data: {data}")
print()
print(f"Mean: {np.mean(data):.2f}")  # Average for normalization
print(f"Median: {np.median(data)}")  # Robust to outliers
print(f"Std Dev: {np.std(data):.2f}")  # For standardization
print(f"Variance: {np.var(data):.2f}")  # For explained variance
print(f"Sum: {np.sum(data)}")  # Total loss, etc.
print(f"Min: {np.min(data)}, Max: {np.max(data)}")  # For scaling
print(f"Argmin: {np.argmin(data)}, Argmax: {np.argmax(data)}")  # For class prediction

# ============================================================
# 🎯 CONCRETE ML EXAMPLES
# ============================================================

# Example 1: Feature Standardization (Z-score normalization)
# Formula: z = (x - mean) / std
# This transforms data to have mean=0 and std=1
print("\n" + "=" * 50)
print("CONCRETE EXAMPLE 1: Feature Standardization")
print("=" * 50)
raw_feature = np.array([100, 150, 200, 250, 300])  # e.g., house prices in $1000s
standardized = (raw_feature - np.mean(raw_feature)) / np.std(raw_feature)
print(f"Raw feature: {raw_feature}")
print(f"Standardized: {np.round(standardized, 3)}")
print(f"New mean: {np.mean(standardized):.6f} (≈ 0)")
print(f"New std: {np.std(standardized):.6f} (≈ 1)")

# Example 2: Min-Max Scaling
# Formula: x_scaled = (x - min) / (max - min)
# This transforms data to range [0, 1]
print("\n" + "=" * 50)
print("CONCRETE EXAMPLE 2: Min-Max Scaling")
print("=" * 50)
min_max_scaled = (raw_feature - np.min(raw_feature)) / (
    np.max(raw_feature) - np.min(raw_feature)
)
print(f"Raw feature: {raw_feature}")
print(f"Min-Max scaled: {min_max_scaled}")

# Example 3: argmax for Classification
# After softmax, argmax gives the predicted class
print("\n" + "=" * 50)
print("CONCRETE EXAMPLE 3: argmax for Classification")
print("=" * 50)
# Simulated softmax output for 3 classes (probabilities sum to 1)
softmax_output = np.array([0.1, 0.7, 0.2])  # Probabilities for classes 0, 1, 2
predicted_class = np.argmax(softmax_output)
print(f"Softmax probabilities: {softmax_output}")
print(
    f"Predicted class: {predicted_class} (highest probability: {softmax_output[predicted_class]})"
)

Data: [23 45 12 67 34 89 21 56 43]

Mean: 43.33
Median: 43.0
Std Dev: 23.07
Variance: 532.22
Sum: 390
Min: 12, Max: 89
Argmin: 2, Argmax: 5

CONCRETE EXAMPLE 1: Feature Standardization
Raw feature: [100 150 200 250 300]
Standardized: [-1.414 -0.707  0.     0.707  1.414]
New mean: 0.000000 (≈ 0)
New std: 1.000000 (≈ 1)

CONCRETE EXAMPLE 2: Min-Max Scaling
Raw feature: [100 150 200 250 300]
Min-Max scaled: [0.   0.25 0.5  0.75 1.  ]

CONCRETE EXAMPLE 3: argmax for Classification
Softmax probabilities: [0.1 0.7 0.2]
Predicted class: 1 (highest probability: 0.7)


### 4.3 Aggregation Along Axes

In [27]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix:")
print(matrix)
print()

print(f"Sum of all: {np.sum(matrix)}")
print(f"Sum along axis 0 (columns): {np.sum(matrix, axis=0)}")
print(f"Sum along axis 1 (rows): {np.sum(matrix, axis=1)}")
print()
print(f"Mean of each column: {np.mean(matrix, axis=0)}")
print(f"Mean of each row: {np.mean(matrix, axis=1)}")

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sum of all: 45
Sum along axis 0 (columns): [12 15 18]
Sum along axis 1 (rows): [ 6 15 24]

Mean of each column: [4. 5. 6.]
Mean of each row: [2. 5. 8.]


### 💡 Understanding Axes

- **axis=0**: Operations along rows (collapse rows, keep columns)
- **axis=1**: Operations along columns (collapse columns, keep rows)

Think of it as: "which axis do I want to reduce/eliminate?"

---
## 5. Reshaping Arrays

**Reshaping is CRITICAL in ML** - Most ML errors come from shape mismatches!

**Common shape patterns in ML:**
- `(n_samples, n_features)` - Standard sklearn input
- `(batch_size, channels, height, width)` - CNN input (PyTorch)
- `(batch_size, height, width, channels)` - CNN input (TensorFlow)
- `(batch_size, seq_len, features)` - RNN/Transformer input

| Operation | ML Use Case |
|-----------|-------------|
| `reshape(-1, 1)` | Convert 1D array to column vector for sklearn |
| `reshape(batch, height, width, channels)` | Prepare images for CNN |
| `flatten()` | Convert image to 1D for fully connected layers |
| `transpose()` | Swap features and samples, attention mechanisms |
| `reshape(-1)` | Flatten predictions for evaluation |

In [28]:
# ============================================================
# RESHAPING FOR ML
# ============================================================
# Reshaping is needed constantly:
# - sklearn expects 2D input: X.reshape(-1, 1) for single feature
# - Neural networks expect specific tensor shapes
# - Image data needs (batch, H, W, C) or (batch, C, H, W)

arr = np.arange(12)
print(f"Original: {arr}")
print(f"Shape: {arr.shape}")

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape: (12,)


In [29]:
# Reshape to 2D
reshaped = arr.reshape(3, 4)
print("Reshaped to (3, 4):")
print(reshaped)

Reshaped to (3, 4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [30]:
# ============================================================
# AUTO-CALCULATE DIMENSION WITH -1
# ============================================================
# The -1 is incredibly useful - NumPy calculates the missing dimension
# Common ML patterns:
#   X.reshape(-1, 1)  -> Single feature column for sklearn
#   X.reshape(1, -1)  -> Single sample row
#   X.reshape(-1)     -> Flatten to 1D (like for y_pred comparison)
#   X.reshape(batch_size, -1)  -> Flatten images keeping batch dimension

auto_reshaped = arr.reshape(4, -1)  # 4 rows, auto columns
print("Auto-reshaped to (4, ?):")
print(auto_reshaped)
print(f"Shape: {auto_reshaped.shape}")

# CONCRETE ML EXAMPLE: Preparing single feature for sklearn
# sklearn expects 2D input, even for a single feature
single_feature = np.array([1.5, 2.3, 3.1, 4.7, 5.2])  # House sizes in 1000 sq ft
print(f"\nOriginal shape: {single_feature.shape}")
X_sklearn = single_feature.reshape(-1, 1)  # -1 means "figure out this dimension"
print(f"Reshaped for sklearn: {X_sklearn.shape}")
print(X_sklearn)

Auto-reshaped to (4, ?):
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Shape: (4, 3)

Original shape: (5,)
Reshaped for sklearn: (5, 1)
[[1.5]
 [2.3]
 [3.1]
 [4.7]
 [5.2]]


In [31]:
# Flatten back to 1D
flattened = reshaped.flatten()
print(f"Flattened: {flattened}")

# Or use ravel (returns view when possible)
raveled = reshaped.ravel()
print(f"Raveled: {raveled}")

Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [32]:
# ============================================================
# TRANSPOSE - Essential for Linear Algebra in ML
# ============================================================
# Transpose swaps rows and columns: shape (m, n) -> (n, m)
#
# Critical ML uses:
# 1. Matrix multiplication: X.T @ X (for normal equation)
# 2. Covariance matrix computation
# 3. Attention mechanisms: Q @ K.T
# 4. Converting row vectors to column vectors
# 5. Feature matrix manipulation

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Original:")
print(matrix)
print(f"Shape: {matrix.shape}")
print()
print("Transposed:")
print(matrix.T)
print(f"Shape: {matrix.T.shape}")

# CONCRETE ML EXAMPLE: Computing X^T @ X for linear regression
# This is part of the normal equation: β = (X^T X)^(-1) X^T y
print("\n--- ML Example: X^T @ X for Normal Equation ---")
X = np.array([[1, 2], [3, 4], [5, 6]])  # 3 samples, 2 features
print(f"X (3 samples, 2 features):\n{X}")
print(f"\nX^T @ X (used in normal equation):")
print(X.T @ X)

Original:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

Transposed:
[[1 4]
 [2 5]
 [3 6]]
Shape: (3, 2)

--- ML Example: X^T @ X for Normal Equation ---
X (3 samples, 2 features):
[[1 2]
 [3 4]
 [5 6]]

X^T @ X (used in normal equation):
[[35 44]
 [44 56]]


---
## 6. Broadcasting

**Broadcasting is NumPy's "magic" for performing operations on arrays of different shapes.**

This is NOT just a convenience feature - it's essential for efficient ML code!

### Why It Matters:
- **Speed**: Broadcasting uses optimized C code, not Python loops
- **Memory**: No need to replicate arrays to match shapes
- **Readability**: Code looks like mathematical notation

### ML Applications of Broadcasting:

| Operation | Without Broadcasting | With Broadcasting |
|-----------|---------------------|------------------|
| Feature normalization | Loop over features | `(X - mean) / std` |
| Bias addition | Loop over samples | `X @ W + b` |
| Distance calculation | Nested loops | `X - centroids[:, np.newaxis]` |
| Softmax denominator | Complex loops | `exp / sum.reshape(-1, 1)` |

In [33]:
# Simple broadcasting: scalar + array
arr = np.array([1, 2, 3])
print(f"arr + 10 = {arr + 10}")

arr + 10 = [11 12 13]


In [34]:
# Broadcasting with 2D arrays
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_vector = np.array([10, 20, 30])

print("Matrix:")
print(matrix)
print(f"Row vector: {row_vector}")
print()
print("Matrix + Row vector:")
print(matrix + row_vector)

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Row vector: [10 20 30]

Matrix + Row vector:
[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [35]:
# Column vector broadcasting
# Redefine matrix for this example (3x3)
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
col_vector = np.array([[100], [200], [300]])
print(f"Matrix shape: {matrix.shape}")
print(f"Column vector shape: {col_vector.shape}")
print()
print("Matrix + Column vector:")
print(matrix + col_vector)

# ============================================================
# 🎯 CONCRETE ML EXAMPLE: Feature Standardization with Broadcasting
# ============================================================
print("\n" + "=" * 60)
print("CONCRETE EXAMPLE: Standardizing Features with Broadcasting")
print("=" * 60)

# Dataset: 5 samples, 3 features (e.g., age, income, credit_score)
X = np.array(
    [
        [25, 50000, 650],
        [35, 75000, 720],
        [45, 100000, 680],
        [30, 60000, 700],
        [55, 120000, 750],
    ],
    dtype=float,
)

print("Original data (5 samples, 3 features):")
print(f"  Columns: [age, income, credit_score]")
print(X)

# Calculate mean and std for each feature (column)
mean = np.mean(X, axis=0)  # Shape: (3,)
std = np.std(X, axis=0)  # Shape: (3,)
print(f"\nFeature means: {mean}")
print(f"Feature stds:  {np.round(std, 2)}")

# Standardize using broadcasting!
# X shape: (5, 3), mean shape: (3,), std shape: (3,)
# Broadcasting automatically applies to each row
X_standardized = (X - mean) / std

print(f"\nStandardized data (mean≈0, std≈1 per column):")
print(np.round(X_standardized, 3))

# Verify
print(f"\nVerification:")
print(f"  Column means: {np.round(np.mean(X_standardized, axis=0), 10)}")
print(f"  Column stds:  {np.round(np.std(X_standardized, axis=0), 10)}")

Matrix shape: (3, 3)
Column vector shape: (3, 1)

Matrix + Column vector:
[[101 102 103]
 [204 205 206]
 [307 308 309]]

CONCRETE EXAMPLE: Standardizing Features with Broadcasting
Original data (5 samples, 3 features):
  Columns: [age, income, credit_score]
[[2.5e+01 5.0e+04 6.5e+02]
 [3.5e+01 7.5e+04 7.2e+02]
 [4.5e+01 1.0e+05 6.8e+02]
 [3.0e+01 6.0e+04 7.0e+02]
 [5.5e+01 1.2e+05 7.5e+02]]

Feature means: [3.8e+01 8.1e+04 7.0e+02]
Feature stds:  [1.07700e+01 2.57682e+04 3.40600e+01]

Standardized data (mean≈0, std≈1 per column):
[[-1.207 -1.203 -1.468]
 [-0.279 -0.233  0.587]
 [ 0.65   0.737 -0.587]
 [-0.743 -0.815  0.   ]
 [ 1.578  1.513  1.468]]

Verification:
  Column means: [0. 0. 0.]
  Column stds:  [1. 1. 1.]


### Broadcasting Rules

1. If arrays have different number of dimensions, pad the smaller one with 1s on the left
2. Arrays are compatible if dimensions are equal or one of them is 1
3. Output shape is the maximum along each dimension

Example:
```
Array A:  3 x 4
Array B:      4
Padded B: 1 x 4
Result:   3 x 4  ✓ Compatible!
```

---
## 7. Linear Algebra

**Linear algebra is THE mathematical foundation of ML.** Nearly every ML algorithm uses these concepts:

| Concept | ML Application |
|---------|----------------|
| **Matrix Multiplication** | Neural network forward pass, feature transformation |
| **Transpose** | Covariance computation, attention mechanisms |
| **Dot Product** | Similarity measures, attention scores, projections |
| **Inverse** | Solving linear regression (normal equation), Mahalanobis distance |
| **Determinant** | Checking if matrix is invertible, Gaussian distributions |
| **Eigenvalues/vectors** | PCA, understanding covariance, spectral clustering |
| **SVD** | Dimensionality reduction, recommendation systems, data compression |
| **Norm** | Regularization (L1, L2), distance calculations |

### Key Equations in ML:
- **Linear Regression**: $\hat{y} = X\beta$ and $\beta = (X^T X)^{-1} X^T y$
- **Neural Network Layer**: $a = \sigma(Wx + b)$
- **PCA**: Find eigenvectors of covariance matrix $X^T X$
- **Attention**: $\text{Attention}(Q, K, V) = \text{softmax}(QK^T / \sqrt{d_k})V$

In [36]:
# ============================================================
# MATRIX MULTIPLICATION - The Core of Neural Networks
# ============================================================
# Matrix multiplication is THE fundamental operation in ML:
#
# 1. NEURAL NETWORK FORWARD PASS:
#    output = activation(weights @ input + bias)
#    Each layer is just matrix multiplication!
#
# 2. LINEAR REGRESSION:
#    predictions = X @ beta
#
# 3. ATTENTION MECHANISM (Transformers):
#    attention_scores = Q @ K.T  (query times key transpose)
#
# 4. FEATURE TRANSFORMATION:
#    transformed_features = original_features @ transformation_matrix

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix A:")
print(A)
print()
print("Matrix B:")
print(B)
print()

# Method 1: @ operator (Python 3.5+) - PREFERRED
print("A @ B (matrix multiplication):")
print(A @ B)
print()

# Method 2: np.dot
print("np.dot(A, B):")
print(np.dot(A, B))

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

A @ B (matrix multiplication):
[[19 22]
 [43 50]]

np.dot(A, B):
[[19 22]
 [43 50]]


In [37]:
# ⚠️ Important: * is element-wise, @ is matrix multiplication
print("A * B (element-wise):")
print(A * B)
print()
print("A @ B (matrix multiplication):")
print(A @ B)

A * B (element-wise):
[[ 5 12]
 [21 32]]

A @ B (matrix multiplication):
[[19 22]
 [43 50]]


In [38]:
# ============================================================
# DOT PRODUCT - Similarity and Projections
# ============================================================
# The dot product measures how "similar" two vectors are:
#
# 1. COSINE SIMILARITY:
#    cos(theta) = (v1 · v2) / (||v1|| * ||v2||)
#    Used in: Word embeddings (Word2Vec), recommendation systems
#
# 2. ATTENTION SCORES:
#    score = query · key (measures relevance)
#
# 3. LINEAR PREDICTIONS:
#    y = x · weights (weighted sum of features)
#
# 4. PROJECTION:
#    Project v1 onto v2: (v1 · v2 / ||v2||²) * v2

v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print(f"v1 · v2 = {np.dot(v1, v2)}")
print(f"Manual: 1*4 + 2*5 + 3*6 = {1*4 + 2*5 + 3*6}")

# Cosine similarity example
cosine_sim = np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))
print(f"Cosine similarity: {cosine_sim:.4f}")

v1 · v2 = 32
Manual: 1*4 + 2*5 + 3*6 = 32
Cosine similarity: 0.9746


In [39]:
# ============================================================
# MATRIX INVERSE - Solving Linear Systems
# ============================================================
# The inverse A⁻¹ is a matrix such that: A @ A⁻¹ = I (identity)
#
# CRITICAL ML APPLICATIONS:
#
# 1. LINEAR REGRESSION (Normal/Closed-form Solution):
#    β = (X^T X)^(-1) X^T y
#    This directly solves for optimal weights!
#
# 2. RIDGE REGRESSION (L2 Regularization):
#    β = (X^T X + λI)^(-1) X^T y
#    The λI term makes the matrix invertible and prevents overfitting
#
# 3. GAUSSIAN DISTRIBUTIONS:
#    Mahalanobis distance uses covariance inverse: (x-μ)^T Σ^(-1) (x-μ)
#
# 4. KALMAN FILTERS:
#    State estimation uses matrix inverses
#
# DETERMINANT:
# - det(A) ≠ 0 means A is invertible
# - det(A) ≈ 0 means A is "nearly singular" - numerically unstable!
# - Used in multivariate Gaussian: p(x) ∝ 1/sqrt(det(Σ))

A = np.array([[4, 7], [2, 6]])
print("Matrix A:")
print(A)

# Determinant
det = np.linalg.det(A)
print(f"\nDeterminant: {det}")
if abs(det) < 1e-10:
    print("⚠️ Warning: Near-zero determinant - matrix may not be invertible!")
else:
    print("✅ Determinant is non-zero - matrix is invertible")

# Inverse
A_inv = np.linalg.inv(A)
print("\nInverse of A:")
print(A_inv)

# Verify: A @ A_inv should be identity
print("\nA @ A_inv (should be identity):")
print(np.round(A @ A_inv, 10))

# ============================================================
# 🎯 CONCRETE EXAMPLE: Linear Regression vs Ridge Regression
# ============================================================
print("\n" + "=" * 60)
print("CONCRETE EXAMPLE: Linear vs Ridge Regression with NumPy")
print("=" * 60)

# Create sample data: predicting house prices
# Features: [size (1000 sq ft), bedrooms]
X = np.array(
    [
        [1.0, 1],  # Small 1-bed
        [1.5, 2],  # Medium 2-bed
        [2.0, 2],  # Medium 2-bed
        [2.5, 3],  # Large 3-bed
        [3.0, 4],  # Large 4-bed
    ]
)
y = np.array([150, 200, 250, 300, 400])  # Prices in $1000s

print(f"\nFeature matrix X (size, bedrooms):")
print(X)
print(f"\nTarget y (house prices in $1000s): {y}")

# Add bias column (column of 1s) - this is the intercept term
X_with_bias = np.column_stack([np.ones(len(X)), X])
print(f"\nX with bias column (for intercept):")
print(X_with_bias)

# ============================================================
# LINEAR REGRESSION: β = (X^T X)^(-1) X^T y
# ============================================================
beta_linear = np.linalg.inv(X_with_bias.T @ X_with_bias) @ X_with_bias.T @ y
print(f"\n📊 LINEAR REGRESSION coefficients:")
print(f"   Intercept (β₀): {beta_linear[0]:.2f}")
print(f"   Size coef (β₁): {beta_linear[1]:.2f} (per 1000 sq ft)")
print(f"   Bedroom coef (β₂): {beta_linear[2]:.2f} (per bedroom)")

# ============================================================
# RIDGE REGRESSION: β = (X^T X + λI)^(-1) X^T y
# ============================================================
lambda_reg = 1.0  # Regularization strength (hyperparameter)
I = np.eye(X_with_bias.shape[1])  # Identity matrix
I[0, 0] = 0  # Don't regularize the intercept term!

beta_ridge = (
    np.linalg.inv(X_with_bias.T @ X_with_bias + lambda_reg * I) @ X_with_bias.T @ y
)
print(f"\n📊 RIDGE REGRESSION coefficients (λ = {lambda_reg}):")
print(f"   Intercept (β₀): {beta_ridge[0]:.2f}")
print(f"   Size coef (β₁): {beta_ridge[1]:.2f} (per 1000 sq ft)")
print(f"   Bedroom coef (β₂): {beta_ridge[2]:.2f} (per bedroom)")

# Compare predictions
y_pred_linear = X_with_bias @ beta_linear
y_pred_ridge = X_with_bias @ beta_ridge
print(f"\n📈 Predictions comparison:")
print(f"   Actual:         {y}")
print(f"   Linear pred:    {np.round(y_pred_linear, 1)}")
print(f"   Ridge pred:     {np.round(y_pred_ridge, 1)}")

# Show the effect of regularization
print(f"\n💡 Notice: Ridge coefficients are SMALLER (shrunk toward 0)")
print(f"   This prevents overfitting by penalizing large weights!")

Matrix A:
[[4 7]
 [2 6]]

Determinant: 10.000000000000002
✅ Determinant is non-zero - matrix is invertible

Inverse of A:
[[ 0.6 -0.7]
 [-0.2  0.4]]

A @ A_inv (should be identity):
[[ 1. -0.]
 [ 0.  1.]]

CONCRETE EXAMPLE: Linear vs Ridge Regression with NumPy

Feature matrix X (size, bedrooms):
[[1.  1. ]
 [1.5 2. ]
 [2.  2. ]
 [2.5 3. ]
 [3.  4. ]]

Target y (house prices in $1000s): [150 200 250 300 400]

X with bias column (for intercept):
[[1.  1.  1. ]
 [1.  1.5 2. ]
 [1.  2.  2. ]
 [1.  2.5 3. ]
 [1.  3.  4. ]]

📊 LINEAR REGRESSION coefficients:
   Intercept (β₀): 33.33
   Size coef (β₁): 73.33 (per 1000 sq ft)
   Bedroom coef (β₂): 33.33 (per bedroom)

📊 RIDGE REGRESSION coefficients (λ = 1.0):
   Intercept (β₀): 69.31
   Size coef (β₁): 37.57 (per 1000 sq ft)
   Bedroom coef (β₂): 48.15 (per bedroom)

📈 Predictions comparison:
   Actual:         [150 200 250 300 400]
   Linear pred:    [140.  210.  246.7 316.7 386.7]
   Ridge pred:     [155.  222.  240.7 307.7 374.6]

💡 Notic

In [40]:
# ============================================================
# EIGENVALUES & EIGENVECTORS - Foundation of Dimensionality Reduction
# ============================================================
# For a matrix A, eigenvalue λ and eigenvector v satisfy: A @ v = λ * v
# The eigenvector v doesn't change DIRECTION when multiplied by A,
# only gets SCALED by λ.
#
# WHY THIS MATTERS IN ML:
#
# 1. PRINCIPAL COMPONENT ANALYSIS (PCA):
#    - Eigenvectors of covariance matrix = principal components
#    - Eigenvalues = variance explained by each component
#    - Larger eigenvalue = more important direction
#    - Used to reduce dimensions while preserving variance
#
##This helps ML models:
#
# Remove noise
#
# Identify dominant patterns
##
# Compress data efficiently
#
# 2. SPECTRAL CLUSTERING:
#    - Uses eigenvectors of graph Laplacian matrix
#    - Groups similar data points together
#
# 3. GOOGLE'S PAGERANK:
#    - Eigenvector of the web's link matrix
#    - Importance of a page = its eigenvector component
#
# 4. UNDERSTANDING DATA STRUCTURE:
#    - Eigenvectors show main directions of variation
#    - Eigenvalues show how much data varies in each direction
#
# 5. STABILITY ANALYSIS:
#    - Used in analyzing neural network dynamics

M = np.array([[4, 2], [1, 3]])
eigenvalues, eigenvectors = np.linalg.eig(M)

print("Matrix M:")
print(M)
# Eigenvalues are magnitudes — how much variance (or stretching) occurs along each eigenvector direction.
print(f"\nEigenvalues: {eigenvalues}")
print("  → These represent the 'importance' or variance in each direction")
# Eigenvectors describe orientation - the directions along which the data is stretched or compressed.
# Eigenvectors is compressed when its values are less than 1 and stretched when its values are greater than 1.
# Compressed means that the data points are closer together along that direction, while stretched means they are farther apart.
# closer together along a direction means that the data points are more similar to each other in that direction,
# while farther apart means they are more different.
# this tells us that the data varies most along the direction of the first eigenvector (associated with the larger eigenvalue).
# and that the second eigenvector (associated with the smaller eigenvalue) represents a direction with less variance.
# and all that can tell us that the first eigenvector is more important for understanding the structure of the data.
# using that information we can focus on the first eigenvector for dimensionality reduction or feature extraction.
# we do that by projecting the data onto the first eigenvector, which captures the most significant patterns in the data.
# both are relevant but for machine learning purposes we often prioritize the eigenvectors associated with larger eigenvalues.
# we do this because those eigenvectors capture the most significant patterns in the data,
# which are often the most useful for tasks like classification, regression, or clustering.
# focusing on the most important directions helps improve model performance and reduce noise.
# classification is the task of predicting a discrete label (category) for an input based on its features.
# classification is useful for tasks like spam detection, image recognition, or sentiment analysis.
# regression is the task of predicting a continuous value for an input based on its features.
# regression is useful for tasks like predicting house prices, stock prices, or temperatures.
# clustering is the task of grouping similar data points together based on their features.
# clustering is useful for tasks like customer segmentation, image segmentation, or anomaly detection.
print("\nEigenvectors (as columns):")
print(eigenvectors)
print("  → These are the principal directions of the transformation")

# Verify: M @ v = λ * v
print("\n🔍 Verification that M @ v = λ * v:")
for i in range(len(eigenvalues)):
    v = eigenvectors[:, i]
    Mv = M @ v
    lambda_v = eigenvalues[i] * v
    print(f"  Eigenvector {i+1}: M@v = {Mv}, λ*v = {lambda_v}")

# ============================================================
# 🎯 CONCRETE EXAMPLE: PCA from Scratch
# ============================================================
# PCA is useful for dimensionality reduction, noise reduction, and data visualization.
# Steps:
# 1. Center the data (subtract mean)
# 2. Compute covariance matrix
# 3. Get eigenvalues and eigenvectors
# 4. Sort eigenvectors by eigenvalues (importance)
# 5. Project data onto top k eigenvectors (dimensionality reduction)
print("\n" + "=" * 60)
print("CONCRETE EXAMPLE: PCA (Principal Component Analysis)")
print("=" * 60)

# Create 2D data with a clear diagonal pattern
np.random.seed(42)
n_samples = 100

# Data with strong correlation: as x increases, y tends to increase
x = np.random.randn(n_samples)
y = 0.8 * x + 0.3 * np.random.randn(n_samples)  # y is correlated with x
data = np.column_stack([x, y])

print(f"\nOriginal data shape: {data.shape}")
print(f"First 5 samples:\n{data[:5]}")

# Step 1: Center the data (subtract mean)
# Centering the data means that we shift it so that its mean is at the origin (0,0).
# This is important because PCA looks for directions of maximum variance,
# and centering ensures that these directions are not biased by the mean of the data.
data_centered = data - np.mean(data, axis=0)
print(f"\nStep 1 - Data centered (mean subtracted)")

# Step 2: Compute covariance matrix  - shows how every pair of features vary together (positive covariance means they increase together)
# (negative covariance means one increases while the other decreases), and zero covariance means they are independent.
# a single scalar value for each pair of features.
# So the covariance matrix is just a collection of many single covariances.
# this is useful for understanding the relationships between features and for techniques like PCA that rely on these relationships.
cov_matrix = (data_centered.T @ data_centered) / (n_samples - 1)
print(f"\nStep 2 - Covariance matrix:")
print(cov_matrix)

# Step 3: Get eigenvalues and eigenvectors
eigenvalues_pca, eigenvectors_pca = np.linalg.eig(cov_matrix)
print(f"\nStep 3 - Eigenvalues (variance in each direction):")
print(f"  PC1: {eigenvalues_pca[0]:.4f}")
print(f"  PC2: {eigenvalues_pca[1]:.4f}")

# Step 4: Calculate explained variance
# This means how much information (variance) each principal component captures from the data.
# We calculate the ratio of each eigenvalue to the total sum of eigenvalues.
# This helps us understand which components are most important.
# We often choose the top k components that explain most of the variance for dimensionality reduction.
# This is difference from eiganvalues which are just the raw values indicating variance along each principal component.
# this is difference from eiganvectors which are the directions in the feature space.
# we need this part to decide how many principal components to keep based on how much variance we want to retain.
# explained variance gives us a clearer picture of the importance of each principal component.
# principal components are values that tell us how much variance each direction (eigenvector) captures in the data.
# So PC1 explains more variance than PC2, meaning it captures more of the data's structure.
# PC2 still captures some variance, but less than PC1.
# we divide each eigenvalue by the total variance to get a percentage that tells us how important each principal component is.
# we mupltiply by 100 because we want to express it as a percentage.
total_var = np.sum(eigenvalues_pca)
explained_var = eigenvalues_pca / total_var * 100
print(f"\nStep 4 - Explained variance ratio:")
print(f"  PC1 explains: {explained_var[0]:.1f}% of variance")
print(f"  PC2 explains: {explained_var[1]:.1f}% of variance")

# Step 5: Project data onto first principal component (dimensionality reduction!)
pc1 = eigenvectors_pca[:, 0]  # First principal component
data_reduced = data_centered @ pc1  # Project to 1D
print(f"\nStep 5 - Data reduced from 2D to 1D!")
print(f"  Original shape: {data.shape}")
print(f"  Reduced shape: {data_reduced.shape}")
print(f"  First 5 values: {data_reduced[:5]}")

Matrix M:
[[4 2]
 [1 3]]

Eigenvalues: [5. 2.]
  → These represent the 'importance' or variance in each direction

Eigenvectors (as columns):
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]
  → These are the principal directions of the transformation

🔍 Verification that M @ v = λ * v:
  Eigenvector 1: M@v = [4.47213595 2.23606798], λ*v = [4.47213595 2.23606798]
  Eigenvector 2: M@v = [-1.41421356  1.41421356], λ*v = [-1.41421356  1.41421356]

CONCRETE EXAMPLE: PCA (Principal Component Analysis)

Original data shape: (100, 2)
First 5 samples:
[[ 0.49671415 -0.0272399 ]
 [-0.1382643  -0.23680504]
 [ 0.64768854  0.41533648]
 [ 1.52302986  0.9777407 ]
 [-0.23415337 -0.23570841]]

Step 1 - Data centered (mean subtracted)

Step 2 - Covariance matrix:
[[0.82476989 0.62436966]
 [0.62436966 0.55299232]]

Step 3 - Eigenvalues (variance in each direction):
  PC1: 1.3279
  PC2: 0.0499

Step 4 - Explained variance ratio:
  PC1 explains: 96.4% of variance
  PC2 explains: 3.6% of variance

St

### 💡 Key ML Applications of Linear Algebra

| Operation | Algorithm | What It Does |
|-----------|-----------|-------------|
| **Matrix Multiplication** | Neural Networks | Forward pass: `output = W @ input + b` |
| **Matrix Multiplication** | Transformers | Attention: `Q @ K.T` computes similarity scores |
| **Transpose** | All | Shape manipulation, covariance: `X.T @ X` |
| **Inverse** | Linear Regression | Normal equation: `β = (XᵀX)⁻¹ Xᵀy` |
| **Inverse + Identity** | Ridge Regression | Regularized: `β = (XᵀX + λI)⁻¹ Xᵀy` |
| **Eigendecomposition** | PCA | Find principal components (directions of max variance) |
| **Eigendecomposition** | Spectral Clustering | Group data using graph eigenvectors |
| **SVD** | Recommendation | Matrix factorization for user-item predictions |
| **SVD** | NLP | Latent Semantic Analysis for topic modeling |
| **Norms** | Regularization | L1 (Lasso) and L2 (Ridge) penalties |
| **Dot Product** | Word2Vec | Similarity between word embeddings |

### 📝 Quick Reference - When to Use What:
- **Need to solve Ax = b?** → Use `np.linalg.solve(A, b)` (more stable than inverse)
- **Need eigenvalues for PCA?** → Use `np.linalg.eig()` or `np.linalg.svd()`
- **Matrix not invertible?** → Add regularization: `A + λI` or use pseudoinverse `np.linalg.pinv()`
- **Need matrix decomposition?** → SVD: `np.linalg.svd()` works for any matrix

---
## 8. Random Number Generation

**Random numbers are EVERYWHERE in ML:**

| Use Case | Why Randomness? |
|----------|----------------|
| **Weight Initialization** | Neural network weights must start random (not zero!) |
| **Data Shuffling** | Prevents model from learning data order |
| **Train/Test Split** | Random assignment ensures unbiased splits |
| **Dropout** | Randomly disable neurons during training |
| **Data Augmentation** | Random transforms (rotation, flip, noise) |

### ⚠️ CRITICAL: Reproducibility
Always set a **random seed** for reproducible experiments!
This ensures you can reproduce your results exactly.

| **Stochastic Gradient Descent** | Random mini-batch selection |
| **Bootstrapping** | Random resampling for ensemble methods |
| **Monte Carlo Methods** | Random sampling for estimation |

In [41]:
# ============================================================
# SETTING RANDOM SEED - Critical for ML Reproducibility!
# ============================================================
# Without a seed, you get different results every run.
# This makes debugging impossible and papers unreproducible.
#
# Best practices:
# 1. Set seed at the start of every experiment
# 2. Use the same seed when comparing models
# 3. Report your seed in papers/documentation
# 4. For deep learning, also set seeds for PyTorch/TensorFlow

np.random.seed(42)  # 42 is a common choice (Hitchhiker's Guide reference!)

In [42]:
# Random numbers from [0, 1)
rand_uniform = np.random.rand(3, 3)
print("Uniform random (3x3):")
print(rand_uniform)

Uniform random (3x3):
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


In [43]:
# Random integers
rand_int = np.random.randint(1, 100, size=(2, 5))
print("Random integers 1-100 (2x5):")
print(rand_int)

Random integers 1-100 (2x5):
[[24  3 22 53  2]
 [88 30 38  2 64]]


In [44]:
# ============================================================
# NORMAL (GAUSSIAN) DISTRIBUTION - The Most Important Distribution in ML
# ============================================================
# Many things in ML assume or use normal distribution:
#
# 1. WEIGHT INITIALIZATION:
#    - Xavier/Glorot: N(0, 1/n_in)
#    - He initialization: N(0, 2/n_in) for ReLU
#
# 2. ADDITIVE NOISE:
#    - Regularization by adding Gaussian noise
#    - Data augmentation
#
# 3. GAUSSIAN PROCESSES:
#    - Bayesian ML uses Gaussian priors
#
# 4. BATCH NORMALIZATION:
#    - Normalizes activations to ~N(0, 1)

# np.random.randn() gives standard normal: mean=0, std=1
# For custom: mean + std * np.random.randn()

rand_normal = np.random.randn(1000)
print(
    f"Normal distribution - Mean: {rand_normal.mean():.3f}, Std: {rand_normal.std():.3f}"
)

# Custom mean and std (like weight initialization)
custom_normal = 0.01 * np.random.randn(100)  # Small weights for initialization
print(
    f"Small weights init - Mean: {custom_normal.mean():.4f}, Std: {custom_normal.std():.4f}"
)

Normal distribution - Mean: 0.039, Std: 1.051
Small weights init - Mean: 0.0016, Std: 0.0116


In [45]:
# Random choice
options = ["cat", "dog", "bird", "fish"]
choices = np.random.choice(options, size=5)
print(f"Random choices: {choices}")

Random choices: ['cat' 'cat' 'bird' 'cat' 'cat']


In [46]:
# Shuffle array in-place
arr = np.arange(10)
print(f"Original: {arr}")
np.random.shuffle(arr)
print(f"Shuffled: {arr}")

Original: [0 1 2 3 4 5 6 7 8 9]
Shuffled: [4 8 7 9 6 1 3 5 2 0]


---
## 9. Performance: NumPy vs Python Lists

Let's see why NumPy is essential for ML - speed matters!

In [47]:
import time

# Create large data
size = 1_000_000
python_list = list(range(size))
numpy_array = np.arange(size)

print(f"Data size: {size:,} elements")

Data size: 1,000,000 elements


In [48]:
# Python list: square each element
start = time.time()
result_list = [x**2 for x in python_list]
python_time = time.time() - start
print(f"Python list: {python_time:.4f} seconds")

Python list: 0.0529 seconds


In [49]:
# NumPy: square each element
start = time.time()
result_numpy = numpy_array**2
numpy_time = time.time() - start
print(f"NumPy array: {numpy_time:.4f} seconds")

NumPy array: 0.0023 seconds


In [50]:
speedup = python_time / numpy_time
print(f"\n�� NumPy is {speedup:.1f}x faster!")


�� NumPy is 22.8x faster!


---
## 📝 Practice Exercises

Try these exercises to solidify your understanding!

### Exercise 1: Array Creation
Create a 5x5 matrix with values from 1 to 25.

In [51]:
# Your code here
exercise_1 = None  # Replace with your solution
five_d_array = np.array(
    [
        [1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
    ]
)
exercise_1 = five_d_array

# Uncomment to check:
# print(exercise_1)
print(exercise_1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


### Exercise 2: Filtering
Given the array below, find all values that are even AND greater than 10.

In [52]:
data = np.array([5, 12, 7, 18, 3, 22, 15, 8, 30, 11])

# Your code here
exercise_2 = None  # Replace with your solution
exercise_2 = data[data > 10]
exercise_2 = exercise_2[exercise_2 % 2 == 0]
# Expected output: [12, 18, 22, 30]
print(exercise_2)

[12 18 22 30]


### Exercise 3: Matrix Operations
Calculate the mean of each row and each column for the matrix below.

In [53]:
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

# Your code here
row_means = None  # Replace with your solution
col_means = None  # Replace with your solution
row_means = np.mean(matrix, axis=1)
col_means = np.mean(matrix, axis=0)

# Expected: row_means = [20, 50, 80], col_means = [40, 50, 60]
print(f"Row means: {row_means}")
print(f"Column means: {col_means}")

Row means: [20. 50. 80.]
Column means: [40. 50. 60.]


### Exercise 4: Normalization (Common in ML!)
Normalize the array to have values between 0 and 1 using min-max scaling:

$$x_{normalized} = \frac{x - x_{min}}{x_{max} - x_{min}}$$

In [54]:
original = np.array([10, 20, 30, 40, 50])

# Your code here
normalized = None  # Replace with your solution
normalized = (original - np.min(original)) / (np.max(original) - np.min(original))


# Expected output: [0., 0.25, 0.5, 0.75, 1.]
print(f"Normalized: {normalized}")

Normalized: [0.   0.25 0.5  0.75 1.  ]


### Exercise 5: Linear Algebra
Solve the system of linear equations:
```
2x + 3y = 8
4x + 5y = 14
```
Hint: Use `np.linalg.solve(A, b)` where Ax = b

In [55]:
# Your code here
# A coefficient matrix is a 2D array representing the coefficients of variables in linear equations.
# this means that the coefficient matrix A contains the coefficients of the variables in the system of equations.
# coefficient means that the numbers that multiply the variables in the equations.
# b right-hand side is a 1D array representing the constants on the right side of the equations.
#
A = None  # Coefficient matrix
b = None  # Right-hand side
solution = None  # Replace with your solution
A = np.array([[2, 3], [4, 5]])
b = np.array([8, 14])
solution = np.linalg.solve(A, b)

# Expected output: x = 1, y = 2
print(f"Solution: x = {solution[0]}, y = {solution[1]}")

Solution: x = 1.0, y = 2.0


---
## 📋 Solutions

Expand the cells below to see the solutions.

In [56]:
# Solution 1
exercise_1 = np.arange(1, 26).reshape(5, 5)
print("Exercise 1 - 5x5 matrix:")
print(exercise_1)

Exercise 1 - 5x5 matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [57]:
# Solution 2
data = np.array([5, 12, 7, 18, 3, 22, 15, 8, 30, 11])
exercise_2 = data[(data % 2 == 0) & (data > 10)]
print(f"Exercise 2 - Even AND > 10: {exercise_2}")

Exercise 2 - Even AND > 10: [12 18 22 30]


In [58]:
# Solution 3
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
row_means = np.mean(matrix, axis=1)
col_means = np.mean(matrix, axis=0)
print(f"Exercise 3 - Row means: {row_means}")
print(f"Exercise 3 - Column means: {col_means}")

Exercise 3 - Row means: [20. 50. 80.]
Exercise 3 - Column means: [40. 50. 60.]


In [59]:
# Solution 4
original = np.array([10, 20, 30, 40, 50])
normalized = (original - original.min()) / (original.max() - original.min())
print(f"Exercise 4 - Normalized: {normalized}")

Exercise 4 - Normalized: [0.   0.25 0.5  0.75 1.  ]


In [60]:
# Solution 5
A = np.array([[2, 3], [4, 5]])
b = np.array([8, 14])
solution = np.linalg.solve(A, b)
print(f"Exercise 5 - x = {solution[0]}, y = {solution[1]}")

Exercise 5 - x = 1.0, y = 2.0


---
## 🎯 Summary

### Key Concepts Covered

1. **Array Creation**: `np.array()`, `np.zeros()`, `np.ones()`, `np.arange()`, `np.linspace()`
2. **Indexing**: Zero-based, negative indexing, slicing with `[start:stop:step]`
3. **Boolean Indexing**: Filter arrays with conditions
4. **Operations**: Element-wise arithmetic, ufuncs, aggregations
5. **Axes**: `axis=0` for columns, `axis=1` for rows
6. **Broadcasting**: Automatic expansion of arrays for operations
7. **Linear Algebra**: `@` for matrix multiplication, `np.linalg` for advanced ops
8. **Random**: `np.random.seed()`, various distributions

### What's Next?

In the next notebook, we'll dive into **Pandas for Data Manipulation**, where you'll learn to work with real-world tabular data!

---

**Happy Learning! 🚀**